name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # every week (for --pre release tests)

jobs:
  check-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx run check-manifest

  test:
    uses: pyapp-kit/workflows/.github/workflows/test-pyrepo.yml@v1
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pip-post-installs: ${{ matrix.pydantic }}
      pip-install-pre-release: ${{ github.event_name == 'schedule' }}
      report-failures: ${{ github.event_name == 'schedule' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
        os: [ubuntu-latest]
        pydantic: ["'pydantic<1.9'", "'pydantic<2.0'", "'pydantic>=2.0'"]

  test-ome-types:
    uses: pyapp-kit/workflows/.github/workflows/test-dependents.yml@v1
    with:
      python-version: ${{ matrix.python-version }}
      dependency-repo: tlambert03/ome-types
      post-install-cmd: pip install ${{ matrix.pydantic }}
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]
        pydantic: ["'pydantic<2'", "'pydantic>=2'"]

  deploy:
    name: Deploy
    needs: test
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: install
        run: |
          python -m pip install build
          python -m build

      - name: 🚢 Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: "./dist/*"
